#Lets the echi-conveter-create utility know which files and directories to load
dirs_to_create:
    - name: test
    - name: config
    - name: log
    - name: csv
    - name: files
    - name: files/to_process
    - name: files/processed
    - name: db
    - name: db/migrate
    - name: examples
    - name: examples/extended_version12
    - name: examples/schemas
    - name: examples/ascii_csv
    - name: lib
    - name: lib/echi-converter

files_to_copy: 
    - name: History.txt
    - name: License.txt
    - name: Manifest.txt
    - name: README.txt
    - name: Rakefile
    - name: test/test_echi-converter.rb
    - name: test/test_helper.rb
    - name: config/application.yml
    - name: config/database.yml
    - name: config/extended_version12.yml
    - name: config/extended_version13.yml
    - name: config/extended_version14.yml
    - name: config/standard_version12.yml
    - name: config/standard_version13.yml
    - name: config/standard_version14.yml
    - name: db/migrate/001_create_echi_records.rb
    - name: db/migrate/002_create_echi_logs.rb
    - name: db/migrate/003_create_echi_agents.rb
    - name: db/migrate/004_change_log_name_size.rb
    - name: db/migrate/005_change_log_processedat_name.rb
    - name: db/migrate/006_create_echi_reasons.rb
    - name: db/migrate/007_create_echi_cwcs.rb
    - name: db/migrate/008_create_echi_vdns.rb
    - name: db/migrate/009_create_echi_acds.rb
    - name: db/migrate/010_create_echi_splits.rb
    - name: db/migrate/011_create_echi_trunks.rb
    - name: db/migrate/012_create_echi_vectors.rb
    - name: examples/extended_version12/chr0003
    - name: examples/extended_version12/chr0003.txt
    - name: examples/ascii_csv/chr5500.123
    - name: lib/database.rb
    - name: lib/database_presence.rb
    - name: lib/echi-converter.rb
    - name: lib/main.rb
    - name: lib/main_win32.rb
    - name: lib/echi-converter/version.rb
    - name: lib/ftp_fetcher.rb
    - name: examples/schemas/oracle_echi.sql
    - name: examples/db_connect_test.rb
    
files_to_upgrade:
    - name: lib/database.rb
    - name: lib/database_presence.rb
    - name: lib/echi-converter.rb
    - name: lib/main.rb
    - name: lib/main_win32.rb
    - name: lib/echi-converter/version.rb
    - name: lib/ftp_fetcher.rb
    - name: db/migrate/003_create_echi_agents.rb
    - name: db/migrate/004_change_log_name_size.rb
    - name: db/migrate/005_change_log_processedat_name.rb
    - name: db/migrate/006_create_echi_aux_reasons.rb
    - name: db/migrate/007_create_echi_cwcs.rb
    - name: db/migrate/008_create_echi_vdns.rb